[project]
name = "cytokine-plasma"
version = "0.1.0"
description = "Building a ML model to predict survival of patients using plasma cytokine levels"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boruta>=0.4.3",
    "forestplot>=0.4.1",
    "hyperopt>=0.3.0",
    "imbalanced-learn>=0.14.2",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "lifelines==0.30.3",
    "numpy>=1.26.4",
    "pandas>=2.3.3",
    "polars>=1.36.1",
    "pycaret==4.0.0a8",
    "scikit-learn>=1.9.0",
    "scikit-survival==0.28.0",
    "seaborn>=0.13.2",
    "shap==0.52.0",
    "statsmodels>=0.14.6",
]
